-- step 1: create Database
CREATE DATABASE IMT577_MILLION_STAGING

-- step 2: Create Datawarehouse
CREATE OR REPLACE WAREHOUSE IMT577_MILLION_DW_STAGING WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE COMMENT = '';

-- STEP 2.1 - CHANGE THE WORKSPACE TO USE DATAWAREHOUSE
USE WAREHOUSE IMT577_MILLION_DW_STAGING;

--STEP 3: CREATE SNOWFLAKE STAGE FOR ALL TABLES:
CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".CHANNEL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/channel' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".CHANNEL_CATEGORY_STAGE URL = 'azure://sp72storage.blob.core.windows.net/channelcategory' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".CUSTOMER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/customer' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".PRODUCT_STAGE URL = 'azure://sp72storage.blob.core.windows.net/product' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".PRODUCT_CATEGORY_STAGE URL = 'azure://sp72storage.blob.core.windows.net/productcategory' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".PRODUCT_TYPE_STAGE URL = 'azure://sp72storage.blob.core.windows.net/producttype' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".RESELLER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/reseller' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".SALES_DETAIL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/salesdetail' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".SALES_HEADER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/salesheader' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".STORE_STAGE URL = 'azure://sp72storage.blob.core.windows.net/store' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".TARGET_DATA_CHANNEL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/targetdatachannel' DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE "IMT577_MILLION_STAGING"."PUBLIC".TARGET_DATA_PRODUCT_STAGE URL = 'azure://sp72storage.blob.core.windows.net/targetdataproduct' DIRECTORY = ( ENABLE = true );

--STEP 4 CREATE A FILE FORMAT USING FORMAT COMMAND TO DECRIBE THE FORMAT OF THE FILE TO BE IMPORTED
CREATE OR REPLACE FILE FORMAT CSV_SKIP_HEADER
type = 'CSV'
field_delimiter = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
skip_header = 1;

--STEP 5: CREATE TABLES 
--CHANNEL_STAGE
CREATE OR REPLACE TABLE STAGE_CHANNEL (
    ChannelID NUMBER(38,0),
    ChannelCategoryID NUMBER(38,0),
    Channel VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBY VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBY VARCHAR(255)
);

--CHANNEL_CATEGORY
CREATE OR REPLACE TABLE STAGE_CHANNEL_CATEGORY (
    ChanelCATEGORYID NUMBER(38,0),
    ChannelCategory VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBY VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBY VARCHAR(255)
);

--CUSTOMER TABLE
CREATE OR REPLACE TABLE STAGE_CUSTOMER (
    CustomerID VARCHAR(255),
    SubSegmentID NUMBER(38,0),
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    Gender VARCHAR(255),
    EmailAddress VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(255),
    StateProvince VARCHAR(255),
    Country VARCHAR(255),
    PostalCode VARCHAR(255),
    PhoneNumber VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate DATE,
    ModifiedBy VARCHAR(255)
);

--PRODUCT TABLE
CREATE OR REPLACE TABLE STAGE_PRODUCT(
    ProductID NUMBER(38,0),
    ProductTypeID NUMBER(38,0),
    Product VARCHAR(255),
    Color VARCHAR(255),
    Style VARCHAR(255),
    UnitOfMeasureID NUMBER(38,0),
    Weight FLOAT,
    Price FLOAT,
    Cost FLOAT,
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255),
    WholesalePrice FLOAT
);

-- PRODUCTCATEGORY
CREATE OR REPLACE TABLE STAGE_PRODUCT_CATEGORY(
    ProductCategoryID NUMBER(38,0),
    ProductCategory VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255)
  );

  --Product Type Table
  CREATE OR REPLACE TABLE STAGE_PRODUCT_TYPE(
    ProductTypeID NUMBER(38,0),
    ProductCategoryID NUMBER(38,0),
    ProductType VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255)
  );

  --Reseller Table 
  CREATE OR REPLACE TABLE STAGE_RESELLER (
    ResellerID VARCHAR(255),
    Contact VARCHAR(255),
    EmailAddress VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(255),
    StateProvince VARCHAR(255),
    Country VARCHAR(255),
    PostalCode VARCHAR(255),
    PhoneNumber VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255),
    ResellerName VARCHAR(255)
);

--Sales Detail
CREATE OR REPLACE TABLE STAGE_SALES_DETAIL (
    SalesDetailID NUMBER(38,0),
    SalesHeaderID NUMBER(38,0),
    ProductID NUMBER(38,0),
    SalesQuantity NUMBER(38,8),
    SalesAmount FLOAT,
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255)
);

--SALES HEADER TABLE
CREATE OR REPLACE TABLE STAGE_SALES_HEADER (
    SalesHeaderID NUMBER(38,0),
    Date VARCHAR(255),
    ChannelID NUMBER(38,0),
    StoreID NUMBER(38,0),
    CustomerID VARCHAR(255),
    ResellerID VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255)
);

--STORE TABLE
CREATE OR REPLACE TABLE STAGE_STORE (
    StoreID NUMBER(38,0),
    SubSegmentID NUMBER(38,0),
    StoreNumber NUMBER(38,0),
    StoreManager VARCHAR(255),
    Address VARCHAR(255),
    City VARCHAR(255),
    StateProvince VARCHAR(255),
    Country VARCHAR(255),
    PostalCode VARCHAR(255),
    PhoneNumber VARCHAR(255),
    CreatedDate VARCHAR(255),
    CreatedBy VARCHAR(255),
    ModifiedDate VARCHAR(255),
    ModifiedBy VARCHAR(255)
);

--TARGET DATA CHANNEL TABLE
CREATE OR REPLACE TABLE STAGE_TARGET_CHANNEL (
   Year VARCHAR(255),
   ChannelName VARCHAR(255),
   TargetName VARCHAR(255),
   TargetSalesAmount FLOAT
);

-- Target Data Product Table
CREATE OR REPLACE TABLE STAGE_TARGET_PRODUCT (
   ProductID NUMBER(38,0),
   Product VARCHAR(255),
   Year VARCHAR(255),
   SalesQuantityTarget FLOAT
);

--STEP 6: COPY DATA FROM STAGE INTO THE TABLE YOU JUST CREATED
--CHANNEL
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_CHANNEL" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."CHANNEL_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--CHANNEL CATEGORY
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_CHANNEL_CATEGORY" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."CHANNEL_CATEGORY_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--CUSTOMER 
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_CUSTOMER" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."CUSTOMER_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--PRODUCT
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_PRODUCT" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."PRODUCT_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--product category
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_PRODUCT_CATEGORY" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."PRODUCT_CATEGORY_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--PRODUCT TYPE
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_PRODUCT_TYPE" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."PRODUCT_TYPE_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--RESELLER
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_RESELLER" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."RESELLER_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- SALES DETAILS
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_SALES_DETAIL" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."SALES_DETAIL_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--SALES HEADER
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_SALES_HEADER" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."SALES_HEADER_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--STORE 
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_STORE" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."STORE_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--TARGET CHANNEL
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_TARGET_CHANNEL" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."TARGET_DATA_CHANNEL_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--TARGET PRODUCT
COPY INTO "IMT577_MILLION_STAGING"."PUBLIC"."STAGE_TARGET_PRODUCT" FROM '@"IMT577_MILLION_STAGING"."PUBLIC"."TARGET_DATA_PRODUCT_STAGE"' 
FILE_FORMAT = '"IMT577_MILLION_STAGING"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

--STEP 7: SELECT STATEMENTS TO VERIFY EVERYTHING LOADED CORRECTLY
SELECT * FROM STAGE_CHANNEL;
SELECT * FROM STAGE_CHANNEL_CATEGORY;
SELECT * FROM STAGE_CUSTOMER;
SELECT * FROM STAGE_PRODUCT;
SELECT * FROM STAGE_PRODUCT_CATEGORY;
SELECT * FROM STAGE_PRODUCT_TYPE;
SELECT * FROM STAGE_RESELLER;
SELECT * FROM STAGE_SALES_DETAIL;
SELECT * FROM STAGE_SALES_HEADER;
SELECT * FROM STAGE_STORE;
SELECT * FROM STAGE_TARGET_CHANNEL;
SELECT * FROM STAGE_TARGET_PRODUCT;